package com.github.hmcts.lifeevents.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;


import jakarta.annotation.Generated;

/**
 * Location that the event happened at
 */

@Schema(name = "Location", description = "Location that the event happened at")
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-06-05T17:22:06.412789+01:00[Europe/London]")
public class Location {

  private String name;

  private String nameQualifier;

  private String registrationDistrict;

  private String subDistrict;

  private String administrativeArea;

  public Location name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name
   * @return name
  */

  @Schema(name = "name", example = "Manchester, Manchester, Metropolitan District of Manchester", description = "Name", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Location nameQualifier(String nameQualifier) {
    this.nameQualifier = nameQualifier;
    return this;
  }

  /**
   * Name qualifier
   * @return nameQualifier
  */

  @Schema(name = "nameQualifier", example = "generated by concatenating registrationDistrict, subDistrict and administrativeArea", description = "Name qualifier", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("nameQualifier")
  public String getNameQualifier() {
    return nameQualifier;
  }

  public void setNameQualifier(String nameQualifier) {
    this.nameQualifier = nameQualifier;
  }

  public Location registrationDistrict(String registrationDistrict) {
    this.registrationDistrict = registrationDistrict;
    return this;
  }

  /**
   * Registration district
   * @return registrationDistrict
  */

  @Schema(name = "registrationDistrict", example = "Manchester", description = "Registration district", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("registrationDistrict")
  public String getRegistrationDistrict() {
    return registrationDistrict;
  }

  public void setRegistrationDistrict(String registrationDistrict) {
    this.registrationDistrict = registrationDistrict;
  }

  public Location subDistrict(String subDistrict) {
    this.subDistrict = subDistrict;
    return this;
  }

  /**
   * Sub-district
   * @return subDistrict
  */

  @Schema(name = "subDistrict", example = "Manchester", description = "Sub-district", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("subDistrict")
  public String getSubDistrict() {
    return subDistrict;
  }

  public void setSubDistrict(String subDistrict) {
    this.subDistrict = subDistrict;
  }

  public Location administrativeArea(String administrativeArea) {
    this.administrativeArea = administrativeArea;
    return this;
  }

  /**
   * Administrative area
   * @return administrativeArea
  */

  @Schema(name = "administrativeArea", example = "Metropolitan District of Manchester", description = "Administrative area", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("administrativeArea")
  public String getAdministrativeArea() {
    return administrativeArea;
  }

  public void setAdministrativeArea(String administrativeArea) {
    this.administrativeArea = administrativeArea;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Location location = (Location) o;
    return Objects.equals(this.name, location.name) &&
        Objects.equals(this.nameQualifier, location.nameQualifier) &&
        Objects.equals(this.registrationDistrict, location.registrationDistrict) &&
        Objects.equals(this.subDistrict, location.subDistrict) &&
        Objects.equals(this.administrativeArea, location.administrativeArea);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, nameQualifier, registrationDistrict, subDistrict, administrativeArea);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Location {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameQualifier: ").append(toIndentedString(nameQualifier)).append("\n");
    sb.append("    registrationDistrict: ").append(toIndentedString(registrationDistrict)).append("\n");
    sb.append("    subDistrict: ").append(toIndentedString(subDistrict)).append("\n");
    sb.append("    administrativeArea: ").append(toIndentedString(administrativeArea)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

