lev:
  ssl:
    publicCertificate: ${LEV_PUBLIC_CERTIFICATE:}
    privateKey: ${LEV_PRIVATE_KEY:}
  bearertoken:
    username: ${LEV_USERNAME:}
    password: ${LEV_PASSWORD:}

spring:
  security:
    oauth2:
      client:
        registration:
          homeoffice:
            client-id: ${LEV_CLIENT_ID}
            client-secret: ${LEV_CLIENT_SECRET}
            authorizationGrantType: password
        provider:
          homeoffice:
            authorization-uri:  ${LEV_DEATH_URL:https://api.lev.homeoffice.gov.uk}
            token-uri:  ${LEV_ACCESS_TOKEN_URI}
  cloud:
    mvc:
      token-relay:
        enabled: false
